# Generated by Django 3.2.7 on 2021-09-17 09:36

import db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "cre_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="作成者ユーザID"
                    ),
                ),
                (
                    "cre_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="作成プログラムID"
                    ),
                ),
                (
                    "cre_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "upd_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="最終更新者ユーザID"
                    ),
                ),
                (
                    "upd_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="最終更新プログラムID"
                    ),
                ),
                (
                    "upd_dt",
                    db.models.UpdateDateTimeField(blank=True, verbose_name="更新日時"),
                ),
                (
                    "cd",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="コード",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="名称"),
                ),
                (
                    "is_foreign",
                    models.BooleanField(default=False, verbose_name="国外企業フラグ"),
                ),
            ],
            options={
                "verbose_name": "製造元",
                "verbose_name_plural": "製造元",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cre_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="作成者ユーザID"
                    ),
                ),
                (
                    "cre_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="作成プログラムID"
                    ),
                ),
                (
                    "cre_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "upd_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="最終更新者ユーザID"
                    ),
                ),
                (
                    "upd_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="最終更新プログラムID"
                    ),
                ),
                (
                    "upd_dt",
                    db.models.UpdateDateTimeField(blank=True, verbose_name="更新日時"),
                ),
                ("order_person", models.CharField(max_length=20, verbose_name="発注者氏名")),
                ("order_day", models.DateTimeField(verbose_name="発注日")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="備考"
                    ),
                ),
                ("is_express", models.BooleanField(verbose_name="お急ぎ便フラグ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("10", "受注済"),
                            ("20", "発送準備中"),
                            ("30", "発送中"),
                            ("90", "発送済"),
                        ],
                        max_length=2,
                        verbose_name="ステータス",
                    ),
                ),
            ],
            options={
                "verbose_name": "注文",
                "verbose_name_plural": "注文",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "cre_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="作成者ユーザID"
                    ),
                ),
                (
                    "cre_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="作成プログラムID"
                    ),
                ),
                (
                    "cre_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "upd_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="最終更新者ユーザID"
                    ),
                ),
                (
                    "upd_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="最終更新プログラムID"
                    ),
                ),
                (
                    "upd_dt",
                    db.models.UpdateDateTimeField(blank=True, verbose_name="更新日時"),
                ),
                (
                    "cd",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="コード",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, unique=True, verbose_name="名称"),
                ),
                ("price", models.IntegerField(verbose_name="価格")),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_manufacturer",
                        to="some_api.manufacturer",
                        verbose_name="製造元",
                    ),
                ),
            ],
            options={
                "verbose_name": "製品",
                "verbose_name_plural": "製品",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cre_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="作成者ユーザID"
                    ),
                ),
                (
                    "cre_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="作成プログラムID"
                    ),
                ),
                (
                    "cre_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "upd_user_id",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="最終更新者ユーザID"
                    ),
                ),
                (
                    "upd_pgm_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="最終更新プログラムID"
                    ),
                ),
                (
                    "upd_dt",
                    db.models.UpdateDateTimeField(blank=True, verbose_name="更新日時"),
                ),
                ("num", models.IntegerField(verbose_name="数量")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetail_order",
                        to="some_api.order",
                        verbose_name="注文",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetail_product",
                        to="some_api.product",
                        verbose_name="製造元",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
